### ISSUE TITLE
Cursor becomes invisible when typing in GNOME Terminal under ibus-array mode

### ISSUE THREAD

**Issue by anthonyfok** [lexical/ibus-array#2]
Hello,

While typing Chinese using ibus-array in GNOME Terminal 3.x, the cursor would become invisible.
This makes text editing with e.g. Vim or GNU Nano inside the GNOME Terminal difficult especially when the user needs to move the cursor around in the text.

Tested with GNOME Terminal 3.22.1 on Debian sid (amd64) as of today, though I have experienced this problem for some time now.  Other input methods do not seem to exhibit this problem.

Many thanks!
Anthony

**Comment by lexical** [comment]
Quick test on gnome terminal 3.18.3, the issue is not found. I will try to install gnome from debian/sid to see if I can reproduce the issue.

Thank for reporting.
