### ISSUE TITLE
行列輸入法表格更新 0.94

### ISSUE THREAD

**Issue by gontera** [lexical/ibus-array#27]
本次 0.90 版新增 CJK Ext-G，並補足原本 Unicode 13.0 中未定義於 CJK Ext-A/B/C/D/E/F/G 中的漢字，並且再微調 
array-shortcode (20210725)。 

檔案已置於我的 github 頁面，網址為 [https://github.com/gontera/array30/tree/master/OpenVanilla](https://github.com/gontera/array30/tree/master/OpenVanilla)，敬請納入下版 ibus-array 更新，感謝！

**Comment by lexical** [comment]
thanks.

**Comment by gontera** [comment]
今天再小更版 0.91（如附檔），並已同步更新於我的 github 頁面。
[OpenVanilla_cin.zip](https://github.com/lexical/ibus-array/files/6925295/OpenVanilla_cin.zip)
