### ISSUE TITLE
Can't compile the code -- no configure file

### ISSUE THREAD

**Issue by DJYeh** [lexical/ibus-array#8]
The instruction asks me to run ./configure. The file does not exist.

**Comment by lexical** [comment]
Please run ./autogen.sh first

**Comment by DJYeh** [comment]
Thanks for the reply. I run autogen.sh and got this message: No package 'ibus-1.0' found.

But I have ibus 1.5.17 installed. What to do now?

**Comment by lexical** [comment]
You will need download the development header file paclages, depending on your distro, it may be different. For Debian/Ubuntu, you can reference the Build-Depends from https://sources.debian.org/src/ibus-array/0.2.1-2/debian/control/
